package com.kong;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Shop".
 */
@Entity(schema = "green_", nameInDb = "Shop")
public class Green_Wine_Shop {

    @Id(autoincrement = true)
    private Long id;
    private String wine_name;
    private String wine_money;
    private String wine_num;
    private Boolean isCheck;

    @Generated
    public Green_Wine_Shop() {
    }

    public Green_Wine_Shop(Long id) {
        this.id = id;
    }

    @Generated
    public Green_Wine_Shop(Long id, String wine_name, String wine_money, String wine_num, Boolean isCheck) {
        this.id = id;
        this.wine_name = wine_name;
        this.wine_money = wine_money;
        this.wine_num = wine_num;
        this.isCheck = isCheck;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWine_name() {
        return wine_name;
    }

    public void setWine_name(String wine_name) {
        this.wine_name = wine_name;
    }

    public String getWine_money() {
        return wine_money;
    }

    public void setWine_money(String wine_money) {
        this.wine_money = wine_money;
    }

    public String getWine_num() {
        return wine_num;
    }

    public void setWine_num(String wine_num) {
        this.wine_num = wine_num;
    }

    public Boolean getIsCheck() {
        return isCheck;
    }

    public void setIsCheck(Boolean isCheck) {
        this.isCheck = isCheck;
    }

}
