package com.kong;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kong.Green_Wine_Shop;

import com.kong.Green_Wine_ShopDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class Green_DaoSession extends AbstractDaoSession {

    private final DaoConfig green_Wine_ShopDaoConfig;

    private final Green_Wine_ShopDao green_Wine_ShopDao;

    public Green_DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        green_Wine_ShopDaoConfig = daoConfigMap.get(Green_Wine_ShopDao.class).clone();
        green_Wine_ShopDaoConfig.initIdentityScope(type);

        green_Wine_ShopDao = new Green_Wine_ShopDao(green_Wine_ShopDaoConfig, this);

        registerDao(Green_Wine_Shop.class, green_Wine_ShopDao);
    }
    
    public void clear() {
        green_Wine_ShopDaoConfig.getIdentityScope().clear();
    }

    public Green_Wine_ShopDao getGreen_Wine_ShopDao() {
        return green_Wine_ShopDao;
    }

}
